apiVersion: v1
kind: Service
metadata:
  name: notificaciones
  labels:
    app: notificaciones
spec:
  selector:
    app: notificaciones
  ports:
    - port: 80
      targetPort: 5005

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notificaciones-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: a30e8ad80d7ce496f87c317e39919031-393841883.us-east-1.elb.amazonaws.com
      http:
        paths:
          - path: /notificaciones
            pathType: Prefix
            backend:
              service:
                name: notificaciones
                port:
                  number: 80
